### ISSUE TITLE
Low quality icons for trash, CD on the desktop.

### ISSUE THREAD

**Issue by svin24** [lah7/Ambiant-MATE#11]
### Describe the problem
For whatever reason Ambiant Mate uses low quality images for trash and CD on the destkop

### Expected behaviour
Higher quality images should be used

### Affected Themes
Only tested Ambiant-MATE

### Screenshots

![image](https://github.com/lah7/Ambiant-MATE/assets/51864332/6271f909-c3d6-49b6-b734-195fb2914ea9)

### Operating System / Environment

Nix OS 23.05

Should note that I installed the icons and themes in .icons and .themes because i am not exactly certain as to where i should put them to be properly FreeDesktop compadible(for things like flatpaks) but that is a separate issue.

**Comment by lah7** [comment]
Can confirm. Happens on Arch Linux too. Running GTK 3.24.38 and MATE 1.26.1. Presumably, Nix OS is using similiar, newer versions.

It works as expected under Ubuntu MATE 22.04, which runs an older GTK 3.24.33 and MATE 1.26.0.

Will have to investigate later.

**Comment by lah7** [comment]
Upon closer investigation, I forgot that the Ambiant-MATE icons inherit Ubuntu's **Humanity** icon theme. You'll need to install this theme in NixOS and re-apply your icon preferences to get those icons.

If `humanity-icon-theme` isn't packaged for your distro, you can download and extract the *.deb from Ubuntu:
https://packages.ubuntu.com/jammy/humanity-icon-theme

In Arch, that package is in the AUR as `humanity-icon-theme`.  I'll update the README.
