### ISSUE TITLE
Change close window button to green (to compliment the theme)

### ISSUE THREAD

**Issue by lah7** [lah7/Ambiant-MATE#4]
> Originally posted at https://github.com/ubuntu-mate/ubuntu-mate-artwork/issues/73

Both RaveFinity's Ambiance/Radiance themes had green buttons, as well as the [`ubuntu-mate-colours`](https://github.com/lah7/ubuntu-mate-colours) project. We could bring that here as an alternate option.

**Comment by lah7** [comment]
For anyone interested in applying this to their theme:

1. Download this file: [Ambiant-MATE-Green-Buttons.tar.gz](https://github.com/lah7/Ambiant-MATE/files/12380104/Ambiant-MATE-Green-Buttons.tar.gz)

2. Extract archive, and drag and drop the replacement folders (`Ambiant-MATE, Radiant-MATE, etc`) to the themes folder.

    In most cases, this would be `/usr/share/themes`. Right click the folder and "Open as Administrator" as root privileges are required.

    ℹ️  **Note** that when the theme is updated, the default will be restored, so it'll need to be copied again.

3. Reload/change the theme to see the changes.

Suppose the wider question is, should this become the default?

**Comment by mz1193** [comment]
The change looks very nice, but personally I feel like destructive actions, such as closing a window, should be a different color than the rest of the accents. Orange works well for this as-is. But that's just my view. :)

**Comment by lah7** [comment]
Though it is a leftover from Ubuntu's Ambiance days, but maybe that's the nostalgic bit about it. Going green would make things similar to [Ambiant-MATE-Colours](https://github.com/lah7/Ambiant-MATE-Colours) which recolours the accent, including the close window button.

Either way, I'm not strongly for or against.  [To the polls 🗳️ (on the Ubuntu MATE community)](https://ubuntu-mate.community/t/poll-should-ambiant-mate-themes-adopt-a-green-close-button/26818/3) for users of the theme to decide!
